### PR TITLE
Avoid having menhir writing .menhir-version

### PR DESCRIPTION
**Pull request by hadrien**
Whenever menhir runs, it writes its own version in .menhir-version.
The side effect is that it changes the git status of the current project
and later on fail detecting what part of the project it has to deploy.

### CODE REVIEW

**Comment by moaazsidat** [comment]
Are there unintended consequences of never 'updating' the version when running `menhir` such as not using the latest version?

**Comment by hugoduncan** [comment]
This doesn't seem to be addressing the issue of menhir failing when the version file has a newline.

The writing of the version file was intended to ensure that whatever menhir version used to run was the specified one.

**Comment by mbelang** [comment]
The issue is that if someone commit the file with a newline at the end then `menhir`, by overriding it will see a local diff in git which makes it silently fail. I mean, if that piece of code is executed then you already have `menhir` so why bother with the version since the version was already specified in the same `.menhir-version` file

**Comment by hugoduncan** [comment]
It was meant to avoid version issues between local and CI, and avoid 'it works on my machine' issues.  Obviously it is causing more issues than it is solving.

**Pull request merged**
